# table definition
table = {
    'table_name'    : 'bpm_details',
    'module_id'     : 'bpm',
    'short_descr'   : 'Bpm detail records',
    'long_descr'    : 'Bpm details for active and completed business processes',
    'sub_types'     : [
        ['line_type', None, [
            ['process', 'Process', ['data_imported'], []],
#           ['start_event', 'Start event', [], []],
#           ['exclusive_gateway', 'Exclusive gateway', [], []],
#           ['inclusive_gateway', 'Inclusive gateway', [], []],
#           ['parallel_gateway', 'Parallel gateway', [], []],
            ['user_task', 'User task', ['iteration', 'repeat', 'data_imported', 'data_exported'], []],
            ['script_task', 'Script task', ['iteration', 'repeat', 'data_imported', 'data_exported'], []],
#           ['sub_manager', 'Sub-process manager', [], []],
            ['sub_process', 'Sub-process', ['iteration', 'repeat'], []],
#           ['boundary_event', 'Boundary event', [], []],
#           ['boundary_event_terminate', 'Boundary event terminated', [], []],
            ['inter_timer_event', 'Intermediate timer event', ['iteration', 'timer_data'], []],
            ['boundary_timer_event', 'Boundary timer event', ['iteration', 'timer_data'], []],
#           ['end_event', 'End event', [], []],
#           ['terminate_event', 'Terminate event', [], []],
            ]],
        ],
    'sub_trans'     : None,
    'sequence'      : None,
    'tree_params'   : None,
    'roll_params'   : None,
    'indexes'       : [
        ['bpm_det_ndx', [['header_row_id', False], ['row_id', False]], None, False]
        ],
    'ledger_col'    : None,
    'defn_company'  : None,
    'data_company'  : None,
    'read_only'     : False,
    }

# column definitions
cols = []
cols.append ({
    'col_name'   : 'row_id',
    'data_type'  : 'AUTO',
    'short_descr': 'Row id',
    'long_descr' : 'Row id',
    'col_head'   : 'Row',
    'key_field'  : 'Y',
    'calculated' : True,
    'allow_null' : False,
    'allow_amend': False,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'dflt_rule'  : None,
    'col_checks' : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'created_id',
    'data_type'  : 'INT',
    'short_descr': 'Created id',
    'long_descr' : 'Created row id',
    'col_head'   : 'Created',
    'key_field'  : 'N',
    'calculated' : False,
    'allow_null' : False,
    'allow_amend': False,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : '0',
    'dflt_rule'  : None,
    'col_checks' : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'deleted_id',
    'data_type'  : 'INT',
    'short_descr': 'Deleted id',
    'long_descr' : 'Deleted row id',
    'col_head'   : 'Deleted',
    'key_field'  : 'N',
    'calculated' : False,
    'allow_null' : False,
    'allow_amend': False,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : '0',
    'dflt_rule'  : None,
    'col_checks' : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'header_row_id',
    'data_type'  : 'INT',
    'short_descr': 'Header row id',
    'long_descr' : 'Header row id',
    'col_head'   : 'Hdr id',
    'key_field'  : 'N',
    'calculated' : False,
    'allow_null' : False,
    'allow_amend': False,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'dflt_rule'  : None,
    'col_checks' : None,
    'fkey'       : ['bpm_headers', 'row_id', None, None, True, None],
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'line_type',
    'data_type'  : 'TEXT',
    'short_descr': 'Line type',
    'long_descr' : 'Line type',
    'col_head'   : 'Line type',
    'key_field'  : 'N',
    'calculated' : False,
    'allow_null' : False,
    'allow_amend': False,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'dflt_rule'  : None,
    'col_checks' : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'element_id',
    'data_type'  : 'TEXT',
    'short_descr': 'Element id',
    'long_descr' : 'Element id',
    'col_head'   : 'Element id',
    'key_field'  : 'N',
    'calculated' : False,
    'allow_null' : False,
    'allow_amend': False,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'dflt_rule'  : None,
    'col_checks' : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'element_name',
    'data_type'  : 'TEXT',
    'short_descr': 'Element name',
    'long_descr' : 'Element name',
    'col_head'   : 'Element name',
    'key_field'  : 'N',
    'calculated' : False,
    'allow_null' : False,
    'allow_amend': False,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'dflt_rule'  : None,
    'col_checks' : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'state',
    'data_type'  : 'TEXT',
    'short_descr': 'State',
    'long_descr' : 'State',
    'col_head'   : 'State',
    'key_field'  : 'N',
    'calculated' : False,
    'allow_null' : False,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'dflt_rule'  : None,
    'col_checks' : None,
    'fkey'       : None,
    'choices'    : [
        ['active', 'Active'],
        ['completed', 'Completed'],
        ['terminated', 'Terminated'],
        ['failed', 'Failed'],
        ],
    })
cols.append ({
    'col_name'   : 'start_time',
    'data_type'  : 'DTM',
    'short_descr': 'Start time',
    'long_descr' : 'Start time',
    'col_head'   : 'Start time',
    'key_field'  : 'N',
    'calculated' : False,
    'allow_null' : False,
    'allow_amend': False,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'dflt_rule'  : None,
    'col_checks' : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'end_time',
    'data_type'  : 'DTM',
    'short_descr': 'End time',
    'long_descr' : 'End time',
    'col_head'   : 'End time',
    'key_field'  : 'N',
    'calculated' : False,
    'allow_null' : True,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'dflt_rule'  : None,
    'col_checks' : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'iteration',
    'data_type'  : 'INT',
    'short_descr': 'Iteration',
    'long_descr' : 'Iteration',
    'col_head'   : 'Iter',
    'key_field'  : 'N',
    'calculated' : False,
    'allow_null' : False,
    'allow_amend': False,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'dflt_rule'  : None,
    'col_checks' : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'repeat',
    'data_type'  : 'INT',
    'short_descr': 'Repeat',
    'long_descr' : 'Repeat count',
    'col_head'   : 'Rep',
    'key_field'  : 'N',
    'calculated' : False,
    'allow_null' : False,
    'allow_amend': False,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'dflt_rule'  : None,
    'col_checks' : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'data_exported',
    'data_type'  : 'JSON',
    'short_descr': 'Data exported',
    'long_descr' : 'Data exported',
    'col_head'   : 'Data exported',
    'key_field'  : 'N',
    'calculated' : False,
    'allow_null' : False,
    'allow_amend': False,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'dflt_rule'  : None,
    'col_checks' : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'data_imported',
    'data_type'  : 'JSON',
    'short_descr': 'Data imported',
    'long_descr' : 'Data imported',
    'col_head'   : 'Data imported',
    'key_field'  : 'N',
    'calculated' : False,
    'allow_null' : True,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'dflt_rule'  : None,
    'col_checks' : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'timer_data',
    'data_type'  : 'TEXT',
    'short_descr': 'Timer data',
    'long_descr' : 'Timer data',
    'col_head'   : 'Timer',
    'key_field'  : 'N',
    'calculated' : False,
    'allow_null' : False,
    'allow_amend': False,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'dflt_rule'  : None,
    'col_checks' : None,
    'fkey'       : None,
    'choices'    : None,
    })

# virtual column definitions
virt = []

# cursor definitions
cursors = []

# actions
actions = []
