from lxml import etree

# table definition
table = {
    'table_name'    : 'db_tables',
    'group_code'    : 'db',
    'short_descr'   : 'Db tables',
    'long_descr'    : 'Database tables',
    'audit_trail'   : True,
    'table_created' : True,
    'default_cursor': None,
    'setup_form'    : None,
    'upd_chks'      : None,
    'del_chks'      : None,
    'table_hooks'   : None,
    'sequence'      : ['seq', ['parent_id'], 'db_table_groups'],
    'defn_company'  : None,
    'data_company'  : None,
    'read_only'     : False,
    }

# column definitions
cols = []
cols.append ({
    'col_name'   : 'row_id',
    'data_type'  : 'AUTO',
    'short_descr': 'Row id',
    'long_descr' : 'Row id',
    'col_head'   : 'Row',
    'key_field'  : 'Y',
    'generated'  : True,
    'allow_null' : False,
    'allow_amend': False,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'created_id',
    'data_type'  : 'INT',
    'short_descr': 'Created id',
    'long_descr' : 'Created row id',
    'col_head'   : 'Created',
    'key_field'  : 'N',
    'generated'  : True,
    'allow_null' : False,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : '0',
    'col_chks'   : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'deleted_id',
    'data_type'  : 'INT',
    'short_descr': 'Deleted id',
    'long_descr' : 'Deleted row id',
    'col_head'   : 'Deleted',
    'key_field'  : 'N',
    'generated'  : True,
    'allow_null' : False,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : '0',
    'col_chks'   : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'table_name',
    'data_type'  : 'TEXT',
    'short_descr': 'Table name',
    'long_descr' : 'Table name',
    'col_head'   : 'Table',
    'key_field'  : 'A',
    'generated'  : False,
    'allow_null' : False,
    'allow_amend': False,
    'max_len'    : 20,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'parent_id',
    'data_type'  : 'INT',
    'short_descr': 'Group id',
    'long_descr' : 'Group id',
    'col_head'   : 'Group',
    'key_field'  : 'N',
    'generated'  : False,
    'allow_null' : False,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : None,
    'fkey'       : ['db_table_groups', 'row_id', 'group_code', 'group_code', False],
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'seq',
    'data_type'  : 'INT',
    'short_descr': 'Sequence',
    'long_descr' : 'Sequence',
    'col_head'   : 'Seq',
    'key_field'  : 'N',
    'generated'  : False,
    'allow_null' : False,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'short_descr',
    'data_type'  : 'TEXT',
    'short_descr': 'Short description',
    'long_descr' : 'Short description',
    'col_head'   : 'Short description',
    'key_field'  : 'N',
    'generated'  : False,
    'allow_null' : False,
    'allow_amend': True,
    'max_len'    : 30,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'long_descr',
    'data_type'  : 'TEXT',
    'short_descr': 'Long description',
    'long_descr' : 'Long description',
    'col_head'   : 'Long description',
    'key_field'  : 'N',
    'generated'  : False,
    'allow_null' : True,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'audit_trail',
    'data_type'  : 'BOOL',
    'short_descr': 'Audit trail?',
    'long_descr' : 'Full audit trail? [Y/N]',
    'col_head'   : 'Audit',
    'key_field'  : 'N',
    'generated'  : False,
    'allow_null' : False,
    'allow_amend': False,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : 'true',
    'col_chks'   : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'table_created',
    'data_type'  : 'BOOL',
    'short_descr': 'Table created?',
    'long_descr' : 'Has table been created in database?',
    'col_head'   : 'Created?',
    'key_field'  : 'N',
    'generated'  : False,
    'allow_null' : False,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'default_cursor',
    'data_type'  : 'TEXT',
    'short_descr': 'Default cursor',
    'long_descr' : 'Default cursor',
    'col_head'   : 'Cursor',
    'key_field'  : 'N',
    'generated'  : False,
    'allow_null' : True,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'setup_form',
    'data_type'  : 'TEXT',
    'short_descr': 'Setup form name',
    'long_descr' : 'Setup form name',
    'col_head'   : 'Form',
    'key_field'  : 'N',
    'generated'  : False,
    'allow_null' : True,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : None,
#   'fkey'       : ['sys_form_defns', 'form_name', None, None, False],
    'fkey'       : None,  # can only set this up after sys_form_defns created
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'upd_chks',
    'data_type'  : 'JSON',
    'short_descr': 'Update checks',
    'long_descr' : 'Checks before insert/update',
    'col_head'   : 'Upd chka',
    'key_field'  : 'N',
    'generated'  : False,
    'allow_null' : True,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'del_chks',
    'data_type'  : 'JSON',
    'short_descr': 'Delete checks',
    'long_descr' : 'Checks before delete',
    'col_head'   : 'Del chka',
    'key_field'  : 'N',
    'generated'  : False,
    'allow_null' : True,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'table_hooks',
    'data_type'  : 'XML',
    'short_descr': 'Table hooks',
    'long_descr' : 'Table hooks',
    'col_head'   : 'Hooka',
    'key_field'  : 'N',
    'generated'  : False,
    'allow_null' : True,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'sequence',
    'data_type'  : 'JSON',
    'short_descr': 'Sequence parameters',
    'long_descr' : 'Sequence parameters (if applicable)',
    'col_head'   : 'Sequence',
    'key_field'  : 'N',
    'generated'  : False,
    'allow_null' : True,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : None,
    'fkey'       : None,
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'defn_company',
    'data_type'  : 'TEXT',
    'short_descr': 'Defn company',
    'long_descr' : 'Company containing table definition',
    'col_head'   : 'Defn',
    'key_field'  : 'N',
    'generated'  : False,
    'allow_null' : True,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : [['no_change', 'Can remove company, but not change it', [
        ['check', '', '$exists', 'is', 'False', ''],
        ['or', '', '$value', 'is', 'None', ''],
        ['or', '', '$value', '=', '$orig', ''],
        ]]],
#   'fkey'       : ['_sys.dir_companies', 'company_id', None, None, False],
    'fkey'       : None,  # can only set this up after dir_companies created
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'data_company',
    'data_type'  : 'TEXT',
    'short_descr': 'Data company',
    'long_descr' : 'Company containing table data',
    'col_head'   : 'Data',
    'key_field'  : 'N',
    'generated'  : False,
    'allow_null' : True,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : [['no_change', 'Can remove company, but not change it', [
        ['check', '', '$exists', 'is', 'False', ''],
        ['or', '', '$value', 'is', 'None', ''],
        ['or', '', '$value', '=', '$orig', ''],
        ]]],
#   'fkey'       : ['_sys.dir_companies', 'company_id', None, None, False],
    'fkey'       : None,  # can only set this up after dir_companies created
    'choices'    : None,
    })
cols.append ({
    'col_name'   : 'read_only',
    'data_type'  : 'BOOL',
    'short_descr': 'Read only?',
    'long_descr' : 'Updating table in other company disallowed?',
    'col_head'   : 'Read only?',
    'key_field'  : 'N',
    'generated'  : False,
    'allow_null' : True,
    'allow_amend': True,
    'max_len'    : 0,
    'db_scale'   : 0,
    'scale_ptr'  : None,
    'dflt_val'   : None,
    'col_chks'   : None,
    'fkey'       : None,
    'choices'    : None,
    })

# virtual column definitions
virt = []
virt.append ({
    'col_name'   : 'children',
    'data_type'  : 'INT',
    'short_descr': 'Children',
    'long_descr' : 'Number of children',
    'col_head'   : '',
    'sql'        : "SELECT count(*) FROM {company}.db_tables b "
                   "WHERE b.parent_id = a.row_id",
    })
virt.append ({
    'col_name'   : 'expandable',
    'data_type'  : 'BOOL',
    'short_descr': 'Expandable?',
    'long_descr' : 'Is this node expandable?',
    'col_head'   : '',
    'sql'        : "SELECT '0'",
    })
virt.append ({
    'col_name'   : 'parent_num',
    'data_type'  : 'INT',
    'short_descr': 'Parent numeric id',
    'long_descr' : 'Parent id - change null to 0',
    'col_head'   : '',
    'sql'        : "SELECT COALESCE(a.parent_id, 0)",
    })

# cursor definitions
cursors = []

cursors.append({
    'cursor_name': 'db_tables',
    'descr': 'Database tables',
    'columns': [
        ('table_name', 160, False, False, False, False, None, None, None, None),
        ('short_descr', 250, True, False, False, False, None, None, None, None),
        ('defn_company', 80, False, True, False, False, None, None, None, None),
        ('table_created', 80, False, True, False, False, None, None, None, None),
        ],
    'filter': [],
    'sequence': [('table_name', False)],
    'default': True
    })
